"""scope ca fragments by generation

Revision ID: 2a3eba67800b
Revises: 481476b302c3
Create Date: 2026-08-16 14:31:36.399113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a3eba67800b'
down_revision: Union[str, Sequence[str], None] = '481476b302c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ca_fragments_fragment_id_key'), 'ca_fragments', type_='unique')
    op.create_unique_constraint('uq_ca_fragment', 'ca_fragments', ['ca_id', 'fragment_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_ca_fragment', 'ca_fragments', type_='unique')
    op.create_unique_constraint(op.f('ca_fragments_fragment_id_key'), 'ca_fragments', ['fragment_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
