"""add ca generations and cross signing

Revision ID: 481476b302c3
Revises: f225d614ea6b
Create Date: 2026-08-16 14:23:54.842411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '481476b302c3'
down_revision: Union[str, Sequence[str], None] = 'f225d614ea6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificate_authorities', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('certificate_authorities', sa.Column('generation', sa.Integer(), nullable=False))
    op.add_column('certificate_authorities', sa.Column('parent_ca_id', sa.Uuid(), nullable=True))
    op.add_column('certificate_authorities', sa.Column('cross_certificate', sa.Text(), nullable=True))
    op.create_index(op.f('ix_certificate_authorities_is_active'), 'certificate_authorities', ['is_active'], unique=False)
    op.create_foreign_key(None, 'certificate_authorities', 'certificate_authorities', ['parent_ca_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'certificate_authorities', type_='foreignkey')
    op.drop_index(op.f('ix_certificate_authorities_is_active'), table_name='certificate_authorities')
    op.drop_column('certificate_authorities', 'cross_certificate')
    op.drop_column('certificate_authorities', 'parent_ca_id')
    op.drop_column('certificate_authorities', 'generation')
    op.drop_column('certificate_authorities', 'is_active')
    # ### end Alembic commands ###
