"""create certificate authority table

Revision ID: 4e44aa807d01
Revises: 47e52d29673b
Create Date: 2026-08-10 21:59:29.458602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e44aa807d01'
down_revision: Union[str, Sequence[str], None] = '47e52d29673b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificate_authorities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('initialized', sa.Boolean(), nullable=False),
    sa.Column('root_certificate', sa.Text(), nullable=True),
    sa.Column('serial_number', sa.String(length=255), nullable=True),
    sa.Column('fingerprint', sa.String(length=255), nullable=True),
    sa.Column('algorithm', sa.String(length=100), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('certificate_authorities')
    # ### end Alembic commands ###
