"""add csr public key fingerprint

Revision ID: 5d1c8fba32a9
Revises: 8efb78c93f27
Create Date: 2026-08-14 13:36:30.085232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d1c8fba32a9'
down_revision: Union[str, Sequence[str], None] = '8efb78c93f27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificate_signing_requests', sa.Column('public_key_fingerprint', sa.String(length=64), nullable=False))
    op.create_index(op.f('ix_certificate_signing_requests_public_key_fingerprint'), 'certificate_signing_requests', ['public_key_fingerprint'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_certificate_signing_requests_public_key_fingerprint'), table_name='certificate_signing_requests')
    op.drop_column('certificate_signing_requests', 'public_key_fingerprint')
    # ### end Alembic commands ###
