"""add certificate signing requests

Revision ID: 7f1c084a620d
Revises: ef83500a4eca
Create Date: 2026-08-13 10:36:59.648245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f1c084a620d'
down_revision: Union[str, Sequence[str], None] = 'ef83500a4eca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificate_signing_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('requester_username', sa.String(length=150), nullable=False),
    sa.Column('csr_pem', sa.Text(), nullable=False),
    sa.Column('algorithm', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_certificate_signing_requests_requester_username'), 'certificate_signing_requests', ['requester_username'], unique=False)
    op.create_index(op.f('ix_certificate_signing_requests_status'), 'certificate_signing_requests', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_certificate_signing_requests_status'), table_name='certificate_signing_requests')
    op.drop_index(op.f('ix_certificate_signing_requests_requester_username'), table_name='certificate_signing_requests')
    op.drop_table('certificate_signing_requests')
    # ### end Alembic commands ###
