"""link issued certificates to csr

Revision ID: 8efb78c93f27
Revises: 7f1c084a620d
Create Date: 2026-08-13 11:09:21.964405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8efb78c93f27'
down_revision: Union[str, Sequence[str], None] = '7f1c084a620d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issued_certificates', sa.Column('csr_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_issued_certificates_csr_id'), 'issued_certificates', ['csr_id'], unique=False)
    op.create_foreign_key(None, 'issued_certificates', 'certificate_signing_requests', ['csr_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'issued_certificates', type_='foreignkey')
    op.drop_index(op.f('ix_issued_certificates_csr_id'), table_name='issued_certificates')
    op.drop_column('issued_certificates', 'csr_id')
    # ### end Alembic commands ###
