"""add ca private key hash

Revision ID: 982ed5f7d42b
Revises: f4af9c1f9ca0
Create Date: 2026-08-12 18:59:41.613243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '982ed5f7d42b'
down_revision: Union[str, Sequence[str], None] = 'f4af9c1f9ca0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificate_authorities', sa.Column('private_key_hash', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('certificate_authorities', 'private_key_hash')
    # ### end Alembic commands ###
