"""add issued certificates

Revision ID: ef83500a4eca
Revises: 982ed5f7d42b
Create Date: 2026-08-13 10:11:45.133597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef83500a4eca'
down_revision: Union[str, Sequence[str], None] = '982ed5f7d42b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issued_certificates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('serial_number', sa.String(length=255), nullable=False),
    sa.Column('certificate_pem', sa.Text(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('issuer', sa.Text(), nullable=False),
    sa.Column('algorithm', sa.String(length=100), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ca_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['ca_id'], ['certificate_authorities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issued_certificates_ca_id'), 'issued_certificates', ['ca_id'], unique=False)
    op.create_index(op.f('ix_issued_certificates_serial_number'), 'issued_certificates', ['serial_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_issued_certificates_serial_number'), table_name='issued_certificates')
    op.drop_index(op.f('ix_issued_certificates_ca_id'), table_name='issued_certificates')
    op.drop_table('issued_certificates')
    # ### end Alembic commands ###
