services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sign-pdf-client
    ports:
      - "8080:80"
    restart: unless-stopped

  api:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: sign-pdf-api
    ports:
      - "8000:8000"
    restart: unless-stopped
