"""remove fragment download state

Revision ID: 23f6b404fdb6
Revises: 7eef3295edab
Create Date: 2026-08-11 15:16:31.332478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '23f6b404fdb6'
down_revision: Union[str, Sequence[str], None] = '7eef3295edab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ca_fragments', 'downloaded')
    op.drop_column('ca_fragments', 'downloaded_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ca_fragments', sa.Column('downloaded_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('ca_fragments', sa.Column('downloaded', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
