"""add fragment id to users

Revision ID: 47e52d29673b
Revises: 1aada0f57894
Create Date: 2026-08-10 21:51:12.312687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47e52d29673b'
down_revision: Union[str, Sequence[str], None] = '1aada0f57894'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fragment_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'users', ['fragment_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'fragment_id')
    # ### end Alembic commands ###
