"""create ca fragments table

Revision ID: aa61adff5aee
Revises: 4e44aa807d01
Create Date: 2026-08-11 14:05:07.583234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa61adff5aee'
down_revision: Union[str, Sequence[str], None] = '4e44aa807d01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ca_fragments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fragment_id', sa.Integer(), nullable=False),
    sa.Column('owner_username', sa.Text(), nullable=False),
    sa.Column('encrypted_content', sa.Text(), nullable=False),
    sa.Column('downloaded', sa.Boolean(), nullable=False),
    sa.Column('downloaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ca_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['ca_id'], ['certificate_authorities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fragment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ca_fragments')
    # ### end Alembic commands ###
