"""add certificate revocation fields

Revision ID: f225d614ea6b
Revises: 5d1c8fba32a9
Create Date: 2026-08-14 14:35:39.836252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f225d614ea6b'
down_revision: Union[str, Sequence[str], None] = '5d1c8fba32a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issued_certificates', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('issued_certificates', sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('issued_certificates', sa.Column('revocation_reason', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_issued_certificates_status'), 'issued_certificates', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_issued_certificates_status'), table_name='issued_certificates')
    op.drop_column('issued_certificates', 'revocation_reason')
    op.drop_column('issued_certificates', 'revoked_at')
    op.drop_column('issued_certificates', 'status')
    # ### end Alembic commands ###
