"""remove fragment download state

Revision ID: f4af9c1f9ca0
Revises: 23f6b404fdb6
Create Date: 2026-08-11 15:22:34.364540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f4af9c1f9ca0'
down_revision: Union[str, Sequence[str], None] = '23f6b404fdb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificate_authorities', sa.Column('public_key', sa.Text(), nullable=False))
    op.alter_column('certificate_authorities', 'root_certificate',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('certificate_authorities', 'serial_number',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('certificate_authorities', 'fingerprint',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('certificate_authorities', 'algorithm',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               nullable=False)
    op.alter_column('certificate_authorities', 'issued_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('certificate_authorities', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_column('certificate_authorities', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificate_authorities', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.alter_column('certificate_authorities', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('certificate_authorities', 'issued_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('certificate_authorities', 'algorithm',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('certificate_authorities', 'fingerprint',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('certificate_authorities', 'serial_number',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('certificate_authorities', 'root_certificate',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('certificate_authorities', 'public_key')
    # ### end Alembic commands ###
