server {
    listen 80;
    server_name _;


    # =========================================================
    # CA SERVICE
    # =========================================================

    location /api/ {
        proxy_pass http://ca-service:8000;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }


    # =========================================================
    # SIGN PDF CLIENT API
    # =========================================================

    location /client-api/ {
        proxy_pass http://sign-pdf-api:9000/api/;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }


    # =========================================================
    # SIGN PDF CLIENT FRONTEND
    # =========================================================

    location /client/ {
        proxy_pass http://sign-pdf-client:80/;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }


    # =========================================================
    # CA FRONTEND
    # =========================================================

    location / {
        proxy_pass http://ca-frontend:80;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}